services:
  plate_rec:
    build: .
    container_name: plate_rec
    ports:
      - "8989:8989"
    volumes:
      - .:/project
    environment:
      - TZ=Asia/Bishkek
    deploy:  
      resources:
        reservations:      
          devices:
            - driver: nvidia          
              count: all
              capabilities: [ gpu ]